export const KNOWN_EVENTS = new Set([
  'upload_started',
  'conversion_succeeded',
  'conversion_failed',
  'deck_downloaded',
  'chat_message_sent',
  'chat_attachment_added',
  'upload_error_chat_shown',
  'upload_error_chat_engaged',
  'upload_error_chat_resolved_retry',
  'upload_empty_deck_chat_shown',
  'upload_empty_deck_chat_engaged',
  'paywall_shown',
  'paywall_upgrade_clicked',
  'purchase',
  'photo_entry_point_viewed',
  'photo_entry_point_clicked',
  'photo_upload_started',
  'photo_quota_reached',
  'sidebar_auto_minimize_fired',
  'sidebar_auto_minimize_reverted',
  'card_size_selected',
  'notion_column_mapping_submitted',
  'database_preview_viewed',
  'convert_clicked_from_preview',
  'upload_ai_off_badge_viewed',
  'upload_ai_off_badge_clicked',
  'upload_ai_on_badge_viewed',
  'upload_ai_on_badge_clicked',
  'upload_ai_anon_badge_viewed',
  'upload_ai_anon_badge_clicked',
  'home_ai_anon_badge_viewed',
  'home_ai_anon_badge_clicked',
  'home_card_options_link_clicked',
  'paywall_dismissed',
  'pricing_left',
  'upload_failed',
  'cancel_during_generating',
  'transform_apkg_submitted',
  'transform_apkg_succeeded',
  'transform_apkg_handoff_received',
] as const);

export type KnownEvent = typeof KNOWN_EVENTS extends Set<infer T> ? T : never;
