// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.abandoned_checkout_recovery_emails */
export type AbandonedCheckoutRecoveryEmailsSessionId = string & { __brand: 'public.abandoned_checkout_recovery_emails' };

/** Represents the table public.abandoned_checkout_recovery_emails */
export default interface AbandonedCheckoutRecoveryEmails {
  session_id: AbandonedCheckoutRecoveryEmailsSessionId;

  user_email: string;

  sent_at: Date;

  token: string | null;
}

/** Represents the initializer for the table public.abandoned_checkout_recovery_emails */
export interface AbandonedCheckoutRecoveryEmailsInitializer {
  session_id: AbandonedCheckoutRecoveryEmailsSessionId;

  user_email: string;

  /** Default value: CURRENT_TIMESTAMP */
  sent_at?: Date;

  token?: string | null;
}

/** Represents the mutator for the table public.abandoned_checkout_recovery_emails */
export interface AbandonedCheckoutRecoveryEmailsMutator {
  session_id?: AbandonedCheckoutRecoveryEmailsSessionId;

  user_email?: string;

  sent_at?: Date;

  token?: string | null;
}
