// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.anonymous_passes */
export type AnonymousPassesId = number & { __brand: 'public.anonymous_passes' };

/** Represents the table public.anonymous_passes */
export default interface AnonymousPasses {
  id: AnonymousPassesId;

  stripe_session_id: string;

  kind: string;

  expires_at: Date;

  payment_intent_id: string;

  created_at: Date;
}

/** Represents the initializer for the table public.anonymous_passes */
export interface AnonymousPassesInitializer {
  /** Default value: nextval('anonymous_passes_id_seq'::regclass) */
  id?: AnonymousPassesId;

  stripe_session_id: string;

  kind: string;

  expires_at: Date;

  payment_intent_id: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.anonymous_passes */
export interface AnonymousPassesMutator {
  id?: AnonymousPassesId;

  stripe_session_id?: string;

  kind?: string;

  expires_at?: Date;

  payment_intent_id?: string;

  created_at?: Date;
}
