// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.api_key_usage */
export type ApiKeyUsageId = number & { __brand: 'public.api_key_usage' };

/** Represents the table public.api_key_usage */
export default interface ApiKeyUsage {
  id: ApiKeyUsageId;

  user_id: number;

  month: Date;

  cards: number;

  warned_at: Date | null;
}

/** Represents the initializer for the table public.api_key_usage */
export interface ApiKeyUsageInitializer {
  /** Default value: nextval('api_key_usage_id_seq'::regclass) */
  id?: ApiKeyUsageId;

  user_id: number;

  month: Date;

  /** Default value: 0 */
  cards?: number;

  warned_at?: Date | null;
}

/** Represents the mutator for the table public.api_key_usage */
export interface ApiKeyUsageMutator {
  id?: ApiKeyUsageId;

  user_id?: number;

  month?: Date;

  cards?: number;

  warned_at?: Date | null;
}
