// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.api_keys */
export type ApiKeysId = number & { __brand: 'public.api_keys' };

/** Represents the table public.api_keys */
export default interface ApiKeys {
  id: ApiKeysId;

  user_id: UsersId;

  name: string;

  key_hash: string;

  prefix: string;

  last_used_at: Date | null;

  created_at: Date;

  revoked_at: Date | null;
}

/** Represents the initializer for the table public.api_keys */
export interface ApiKeysInitializer {
  /** Default value: nextval('api_keys_id_seq'::regclass) */
  id?: ApiKeysId;

  user_id: UsersId;

  name: string;

  key_hash: string;

  prefix: string;

  last_used_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  revoked_at?: Date | null;
}

/** Represents the mutator for the table public.api_keys */
export interface ApiKeysMutator {
  id?: ApiKeysId;

  user_id?: UsersId;

  name?: string;

  key_hash?: string;

  prefix?: string;

  last_used_at?: Date | null;

  created_at?: Date;

  revoked_at?: Date | null;
}
