// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.apple_transactions */
export type AppleTransactionsId = number & { __brand: 'public.apple_transactions' };

/** Represents the table public.apple_transactions */
export default interface AppleTransactions {
  id: AppleTransactionsId;

  user_id: UsersId;

  transaction_id: string;

  product_id: string;

  environment: string;

  expires_at: Date | null;

  created_at: Date;
}

/** Represents the initializer for the table public.apple_transactions */
export interface AppleTransactionsInitializer {
  /** Default value: nextval('apple_transactions_id_seq'::regclass) */
  id?: AppleTransactionsId;

  user_id: UsersId;

  transaction_id: string;

  product_id: string;

  environment: string;

  expires_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.apple_transactions */
export interface AppleTransactionsMutator {
  id?: AppleTransactionsId;

  user_id?: UsersId;

  transaction_id?: string;

  product_id?: string;

  environment?: string;

  expires_at?: Date | null;

  created_at?: Date;
}
