// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.conversion_output_stats */
export type ConversionOutputStatsSource = string & { __brand: 'public.conversion_output_stats' };

/** Represents the table public.conversion_output_stats */
export default interface ConversionOutputStats {
  source: ConversionOutputStatsSource;

  decks: string;

  cards: string;

  empty_back_cards: string;

  first_seen: Date;

  last_seen: Date;
}

/** Represents the initializer for the table public.conversion_output_stats */
export interface ConversionOutputStatsInitializer {
  source: ConversionOutputStatsSource;

  /** Default value: '0'::bigint */
  decks?: string;

  /** Default value: '0'::bigint */
  cards?: string;

  /** Default value: '0'::bigint */
  empty_back_cards?: string;

  /** Default value: CURRENT_TIMESTAMP */
  first_seen?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  last_seen?: Date;
}

/** Represents the mutator for the table public.conversion_output_stats */
export interface ConversionOutputStatsMutator {
  source?: ConversionOutputStatsSource;

  decks?: string;

  cards?: string;

  empty_back_cards?: string;

  first_seen?: Date;

  last_seen?: Date;
}
