// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.deck_shares */
export type DeckSharesId = number & { __brand: 'public.deck_shares' };

/** Represents the table public.deck_shares */
export default interface DeckShares {
  id: DeckSharesId;

  owner: UsersId;

  upload_key: string;

  token: string;

  created_at: Date;

  revoked_at: Date | null;

  view_count: number;

  is_public: boolean;

  title: string | null;

  card_count: number | null;
}

/** Represents the initializer for the table public.deck_shares */
export interface DeckSharesInitializer {
  /** Default value: nextval('deck_shares_id_seq'::regclass) */
  id?: DeckSharesId;

  owner: UsersId;

  upload_key: string;

  token: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  revoked_at?: Date | null;

  /** Default value: 0 */
  view_count?: number;

  /** Default value: false */
  is_public?: boolean;

  title?: string | null;

  card_count?: number | null;
}

/** Represents the mutator for the table public.deck_shares */
export interface DeckSharesMutator {
  id?: DeckSharesId;

  owner?: UsersId;

  upload_key?: string;

  token?: string;

  created_at?: Date;

  revoked_at?: Date | null;

  view_count?: number;

  is_public?: boolean;

  title?: string | null;

  card_count?: number | null;
}
