// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.deleted_user_usage */
export type DeletedUserUsageEmailSha256 = string & { __brand: 'public.deleted_user_usage' };

/** Represents the table public.deleted_user_usage */
export default interface DeletedUserUsage {
  email_sha256: DeletedUserUsageEmailSha256;

  cards_used_this_month: number;

  cards_month_started_at: Date | null;

  pdf_prints_this_month: number;

  prints_month_started_at: Date | null;

  deleted_at: Date;
}

/** Represents the initializer for the table public.deleted_user_usage */
export interface DeletedUserUsageInitializer {
  email_sha256: DeletedUserUsageEmailSha256;

  /** Default value: 0 */
  cards_used_this_month?: number;

  cards_month_started_at?: Date | null;

  /** Default value: 0 */
  pdf_prints_this_month?: number;

  prints_month_started_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  deleted_at?: Date;
}

/** Represents the mutator for the table public.deleted_user_usage */
export interface DeletedUserUsageMutator {
  email_sha256?: DeletedUserUsageEmailSha256;

  cards_used_this_month?: number;

  cards_month_started_at?: Date | null;

  pdf_prints_this_month?: number;

  prints_month_started_at?: Date | null;

  deleted_at?: Date;
}
