// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.developer_tiers */
export type DeveloperTiersId = number & { __brand: 'public.developer_tiers' };

/** Represents the table public.developer_tiers */
export default interface DeveloperTiers {
  id: DeveloperTiersId;

  tier_key: string;

  stripe_product_id: string;

  stripe_price_id: string;

  monthly_card_limit: number;

  requests_per_minute: number;

  active: boolean;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.developer_tiers */
export interface DeveloperTiersInitializer {
  /** Default value: nextval('developer_tiers_id_seq'::regclass) */
  id?: DeveloperTiersId;

  tier_key: string;

  stripe_product_id: string;

  stripe_price_id: string;

  monthly_card_limit: number;

  requests_per_minute: number;

  /** Default value: true */
  active?: boolean;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.developer_tiers */
export interface DeveloperTiersMutator {
  id?: DeveloperTiersId;

  tier_key?: string;

  stripe_product_id?: string;

  stripe_price_id?: string;

  monthly_card_limit?: number;

  requests_per_minute?: number;

  active?: boolean;

  created_at?: Date;

  updated_at?: Date;
}
