// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.error_events */
export type ErrorEventsId = string & { __brand: 'public.error_events' };

/** Represents the table public.error_events */
export default interface ErrorEvents {
  id: ErrorEventsId;

  source: string;

  message_hash: string;

  message: string;

  stack: string | null;

  url: string | null;

  user_agent: string | null;

  release: string | null;

  user_id: UsersId | null;

  ip_hash: string | null;

  context: unknown | null;

  created_at: Date;
}

/** Represents the initializer for the table public.error_events */
export interface ErrorEventsInitializer {
  /** Default value: nextval('error_events_id_seq'::regclass) */
  id?: ErrorEventsId;

  source: string;

  message_hash: string;

  message: string;

  stack?: string | null;

  url?: string | null;

  user_agent?: string | null;

  release?: string | null;

  user_id?: UsersId | null;

  ip_hash?: string | null;

  context?: unknown | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.error_events */
export interface ErrorEventsMutator {
  id?: ErrorEventsId;

  source?: string;

  message_hash?: string;

  message?: string;

  stack?: string | null;

  url?: string | null;

  user_agent?: string | null;

  release?: string | null;

  user_id?: UsersId | null;

  ip_hash?: string | null;

  context?: unknown | null;

  created_at?: Date;
}
