// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.error_resolutions */
export type ErrorResolutionsMessageHash = string & { __brand: 'public.error_resolutions' };

/** Represents the table public.error_resolutions */
export default interface ErrorResolutions {
  message_hash: ErrorResolutionsMessageHash;

  resolved_at: Date;

  resolved_by: UsersId | null;
}

/** Represents the initializer for the table public.error_resolutions */
export interface ErrorResolutionsInitializer {
  message_hash: ErrorResolutionsMessageHash;

  /** Default value: CURRENT_TIMESTAMP */
  resolved_at?: Date;

  resolved_by?: UsersId | null;
}

/** Represents the mutator for the table public.error_resolutions */
export interface ErrorResolutionsMutator {
  message_hash?: ErrorResolutionsMessageHash;

  resolved_at?: Date;

  resolved_by?: UsersId | null;
}
