// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.feature_flags */
export type FeatureFlagsKey = string & { __brand: 'public.feature_flags' };

/** Represents the table public.feature_flags */
export default interface FeatureFlags {
  key: FeatureFlagsKey;

  value: boolean;

  description: string | null;

  updated_at: Date | null;

  updated_by: UsersId | null;
}

/** Represents the initializer for the table public.feature_flags */
export interface FeatureFlagsInitializer {
  key: FeatureFlagsKey;

  /** Default value: false */
  value?: boolean;

  description?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date | null;

  updated_by?: UsersId | null;
}

/** Represents the mutator for the table public.feature_flags */
export interface FeatureFlagsMutator {
  key?: FeatureFlagsKey;

  value?: boolean;

  description?: string | null;

  updated_at?: Date | null;

  updated_by?: UsersId | null;
}
