// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.feature_interest */
export type FeatureInterestId = number & { __brand: 'public.feature_interest' };

/** Represents the table public.feature_interest */
export default interface FeatureInterest {
  id: FeatureInterestId;

  feature_key: string;

  user_id: UsersId | null;

  anonymous_id: string | null;

  comment: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.feature_interest */
export interface FeatureInterestInitializer {
  /** Default value: nextval('feature_interest_id_seq'::regclass) */
  id?: FeatureInterestId;

  feature_key: string;

  user_id?: UsersId | null;

  anonymous_id?: string | null;

  comment?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.feature_interest */
export interface FeatureInterestMutator {
  id?: FeatureInterestId;

  feature_key?: string;

  user_id?: UsersId | null;

  anonymous_id?: string | null;

  comment?: string | null;

  created_at?: Date;
}
