// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { McpOauthClientsClientId } from './McpOauthClients';
import type { UsersId } from './Users';

/** Identifier type for public.mcp_authorization_codes */
export type McpAuthorizationCodesId = number & { __brand: 'public.mcp_authorization_codes' };

/** Represents the table public.mcp_authorization_codes */
export default interface McpAuthorizationCodes {
  id: McpAuthorizationCodesId;

  code_hash: string;

  client_id: McpOauthClientsClientId;

  user_id: UsersId;

  redirect_uri: string;

  code_challenge: string;

  scopes: unknown;

  resource: string | null;

  expires_at: Date;

  consumed_at: Date | null;

  created_at: Date;
}

/** Represents the initializer for the table public.mcp_authorization_codes */
export interface McpAuthorizationCodesInitializer {
  /** Default value: nextval('mcp_authorization_codes_id_seq'::regclass) */
  id?: McpAuthorizationCodesId;

  code_hash: string;

  client_id: McpOauthClientsClientId;

  user_id: UsersId;

  redirect_uri: string;

  code_challenge: string;

  scopes: unknown;

  resource?: string | null;

  expires_at: Date;

  consumed_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.mcp_authorization_codes */
export interface McpAuthorizationCodesMutator {
  id?: McpAuthorizationCodesId;

  code_hash?: string;

  client_id?: McpOauthClientsClientId;

  user_id?: UsersId;

  redirect_uri?: string;

  code_challenge?: string;

  scopes?: unknown;

  resource?: string | null;

  expires_at?: Date;

  consumed_at?: Date | null;

  created_at?: Date;
}
