// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.mcp_oauth_clients */
export type McpOauthClientsClientId = string & { __brand: 'public.mcp_oauth_clients' };

/** Represents the table public.mcp_oauth_clients */
export default interface McpOauthClients {
  client_id: McpOauthClientsClientId;

  client_name: string | null;

  redirect_uris: unknown;

  grant_types: unknown;

  response_types: unknown;

  scope: string | null;

  token_endpoint_auth_method: string;

  metadata: unknown;

  client_id_issued_at: string;

  created_at: Date;
}

/** Represents the initializer for the table public.mcp_oauth_clients */
export interface McpOauthClientsInitializer {
  client_id: McpOauthClientsClientId;

  client_name?: string | null;

  redirect_uris: unknown;

  grant_types: unknown;

  response_types: unknown;

  scope?: string | null;

  /** Default value: 'none'::character varying */
  token_endpoint_auth_method?: string;

  metadata: unknown;

  client_id_issued_at: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.mcp_oauth_clients */
export interface McpOauthClientsMutator {
  client_id?: McpOauthClientsClientId;

  client_name?: string | null;

  redirect_uris?: unknown;

  grant_types?: unknown;

  response_types?: unknown;

  scope?: string | null;

  token_endpoint_auth_method?: string;

  metadata?: unknown;

  client_id_issued_at?: string;

  created_at?: Date;
}
