// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { McpOauthClientsClientId } from './McpOauthClients';
import type { UsersId } from './Users';

/** Identifier type for public.mcp_refresh_tokens */
export type McpRefreshTokensId = number & { __brand: 'public.mcp_refresh_tokens' };

/** Represents the table public.mcp_refresh_tokens */
export default interface McpRefreshTokens {
  id: McpRefreshTokensId;

  token_hash: string;

  client_id: McpOauthClientsClientId;

  user_id: UsersId;

  scopes: unknown;

  resource: string | null;

  expires_at: Date;

  revoked_at: Date | null;

  created_at: Date;
}

/** Represents the initializer for the table public.mcp_refresh_tokens */
export interface McpRefreshTokensInitializer {
  /** Default value: nextval('mcp_refresh_tokens_id_seq'::regclass) */
  id?: McpRefreshTokensId;

  token_hash: string;

  client_id: McpOauthClientsClientId;

  user_id: UsersId;

  scopes: unknown;

  resource?: string | null;

  expires_at: Date;

  revoked_at?: Date | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.mcp_refresh_tokens */
export interface McpRefreshTokensMutator {
  id?: McpRefreshTokensId;

  token_hash?: string;

  client_id?: McpOauthClientsClientId;

  user_id?: UsersId;

  scopes?: unknown;

  resource?: string | null;

  expires_at?: Date;

  revoked_at?: Date | null;

  created_at?: Date;
}
