// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.mindmaps */
export type MindmapsId = string & { __brand: 'public.mindmaps' };

export interface MindmapData {
  nodes: Array<{ id: string; label: string }>;
  edges: Array<{ source: string; target: string }>;
}

/** Represents the table public.mindmaps */
export default interface Mindmaps {
  id: MindmapsId;

  user_id: UsersId;

  title: string;

  data: MindmapData;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.mindmaps */
export interface MindmapsInitializer {
  /** Default value: gen_random_uuid() */
  id?: MindmapsId;

  user_id: UsersId;

  /** Default value: 'Untitled' */
  title?: string;

  /** Default value: '{"nodes":[],"edges":[]}' */
  data?: MindmapData;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.mindmaps */
export interface MindmapsMutator {
  id?: MindmapsId;

  user_id?: UsersId;

  title?: string;

  data?: MindmapData;

  created_at?: Date;

  updated_at?: Date;
}
