// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.oauth_identities */
export type OauthIdentitiesId = number & { __brand: 'public.oauth_identities' };

/** Represents the table public.oauth_identities */
export default interface OauthIdentities {
  id: OauthIdentitiesId;

  provider: string;

  subject: string;

  user_id: UsersId;

  created_at: Date;
}

/** Represents the initializer for the table public.oauth_identities */
export interface OauthIdentitiesInitializer {
  /** Default value: nextval('oauth_identities_id_seq'::regclass) */
  id?: OauthIdentitiesId;

  provider: string;

  subject: string;

  user_id: UsersId;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.oauth_identities */
export interface OauthIdentitiesMutator {
  id?: OauthIdentitiesId;

  provider?: string;

  subject?: string;

  user_id?: UsersId;

  created_at?: Date;
}
