// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.parse_path_signatures */
export type ParsePathSignaturesParsePath = string & { __brand: 'public.parse_path_signatures' };

/** Represents the table public.parse_path_signatures */
export default interface ParsePathSignatures {
  parse_path: ParsePathSignaturesParsePath;

  occurrences: string;

  first_seen: Date;

  last_seen: Date;
}

/** Represents the initializer for the table public.parse_path_signatures */
export interface ParsePathSignaturesInitializer {
  parse_path: ParsePathSignaturesParsePath;

  /** Default value: '0'::bigint */
  occurrences?: string;

  /** Default value: CURRENT_TIMESTAMP */
  first_seen?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  last_seen?: Date;
}

/** Represents the mutator for the table public.parse_path_signatures */
export interface ParsePathSignaturesMutator {
  parse_path?: ParsePathSignaturesParsePath;

  occurrences?: string;

  first_seen?: Date;

  last_seen?: Date;
}
