// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.pass_winback_notifications */
export type PassWinbackNotificationsId = number & { __brand: 'public.pass_winback_notifications' };

/** Represents the table public.pass_winback_notifications */
export default interface PassWinbackNotifications {
  id: PassWinbackNotificationsId;

  user_id: UsersId;

  campaign: string;

  token: string;

  notified_at: Date;
}

/** Represents the initializer for the table public.pass_winback_notifications */
export interface PassWinbackNotificationsInitializer {
  /** Default value: nextval('pass_winback_notifications_id_seq'::regclass) */
  id?: PassWinbackNotificationsId;

  user_id: UsersId;

  campaign: string;

  token: string;

  /** Default value: CURRENT_TIMESTAMP */
  notified_at?: Date;
}

/** Represents the mutator for the table public.pass_winback_notifications */
export interface PassWinbackNotificationsMutator {
  id?: PassWinbackNotificationsId;

  user_id?: UsersId;

  campaign?: string;

  token?: string;

  notified_at?: Date;
}
