// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.pause_resume_warning_notices */
export type PauseResumeWarningNoticesId = number & { __brand: 'public.pause_resume_warning_notices' };

/** Represents the table public.pause_resume_warning_notices */
export default interface PauseResumeWarningNotices {
  id: PauseResumeWarningNoticesId;

  subscription_email: string;

  resumes_at: Date;

  sent_at: Date;
}

/** Represents the initializer for the table public.pause_resume_warning_notices */
export interface PauseResumeWarningNoticesInitializer {
  /** Default value: nextval('pause_resume_warning_notices_id_seq'::regclass) */
  id?: PauseResumeWarningNoticesId;

  subscription_email: string;

  resumes_at: Date;

  /** Default value: CURRENT_TIMESTAMP */
  sent_at?: Date;
}

/** Represents the mutator for the table public.pause_resume_warning_notices */
export interface PauseResumeWarningNoticesMutator {
  id?: PauseResumeWarningNoticesId;

  subscription_email?: string;

  resumes_at?: Date;

  sent_at?: Date;
}
