// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.pitch_dismissals */
export type PitchDismissalsId = number & { __brand: 'public.pitch_dismissals' };

/** Represents the table public.pitch_dismissals */
export default interface PitchDismissals {
  id: PitchDismissalsId;

  user_id: UsersId;

  placement: string;

  dismissed_at: Date;
}

/** Represents the initializer for the table public.pitch_dismissals */
export interface PitchDismissalsInitializer {
  /** Default value: nextval('pitch_dismissals_id_seq'::regclass) */
  id?: PitchDismissalsId;

  user_id: UsersId;

  placement: string;

  /** Default value: CURRENT_TIMESTAMP */
  dismissed_at?: Date;
}

/** Represents the mutator for the table public.pitch_dismissals */
export interface PitchDismissalsMutator {
  id?: PitchDismissalsId;

  user_id?: UsersId;

  placement?: string;

  dismissed_at?: Date;
}
