// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.price_lock_in_emails */
export type PriceLockInEmailsId = number & {
  __brand: 'public.price_lock_in_emails';
};

/** Represents the table public.price_lock_in_emails */
export default interface PriceLockInEmails {
  id: PriceLockInEmailsId;

  user_id: UsersId;

  token: string;

  variant: string;

  sent_at: Date;
}

/** Represents the initializer for the table public.price_lock_in_emails */
export interface PriceLockInEmailsInitializer {
  /** Default value: nextval('price_lock_in_emails_id_seq'::regclass) */
  id?: PriceLockInEmailsId;

  user_id: UsersId;

  token: string;

  variant: string;

  /** Default value: CURRENT_TIMESTAMP */
  sent_at?: Date;
}

/** Represents the mutator for the table public.price_lock_in_emails */
export interface PriceLockInEmailsMutator {
  id?: PriceLockInEmailsId;

  user_id?: UsersId;

  token?: string;

  variant?: string;

  sent_at?: Date;
}
