// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.subscription_recovery_notifications */
export type SubscriptionRecoveryNotificationsId = number & {
  __brand: 'public.subscription_recovery_notifications';
};

/** Represents the table public.subscription_recovery_notifications */
export default interface SubscriptionRecoveryNotifications {
  id: SubscriptionRecoveryNotificationsId;

  email_hash: string;

  notified_at: Date;
}

/** Represents the initializer for the table public.subscription_recovery_notifications */
export interface SubscriptionRecoveryNotificationsInitializer {
  /** Default value: nextval('subscription_recovery_notifications_id_seq'::regclass) */
  id?: SubscriptionRecoveryNotificationsId;

  email_hash: string;

  /** Default value: CURRENT_TIMESTAMP */
  notified_at?: Date;
}

/** Represents the mutator for the table public.subscription_recovery_notifications */
export interface SubscriptionRecoveryNotificationsMutator {
  id?: SubscriptionRecoveryNotificationsId;

  email_hash?: string;

  notified_at?: Date;
}
