// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.subscription_claim_tokens */
export type SubscriptionClaimTokensId = number & { __brand: 'public.subscription_claim_tokens' };

/** Represents the table public.subscription_claim_tokens */
export default interface SubscriptionClaimTokens {
  id: SubscriptionClaimTokensId;

  user_id: UsersId;

  stripe_customer_id: string;

  token_hash: string;

  expires_at: Date;

  consumed_at: Date | null;

  created_at: Date;
}

/** Represents the initializer for the table public.subscription_claim_tokens */
export interface SubscriptionClaimTokensInitializer {
  /** Default value: nextval('subscription_claim_tokens_id_seq'::regclass) */
  id?: SubscriptionClaimTokensId;

  user_id: UsersId;

  stripe_customer_id: string;

  token_hash: string;

  expires_at: Date;

  consumed_at?: Date | null;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.subscription_claim_tokens */
export interface SubscriptionClaimTokensMutator {
  id?: SubscriptionClaimTokensId;

  user_id?: UsersId;

  stripe_customer_id?: string;

  token_hash?: string;

  expires_at?: Date;

  consumed_at?: Date | null;

  created_at?: Date;
}
