// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.subscription_claim_audit */
export type SubscriptionClaimAuditId = number & { __brand: 'public.subscription_claim_audit' };

/** Represents the table public.subscription_claim_audit */
export default interface SubscriptionClaimAudit {
  id: SubscriptionClaimAuditId;

  user_id: number;

  email_hash: string;

  ip_hash: string;

  outcome: string;

  created_at: Date;
}

/** Represents the initializer for the table public.subscription_claim_audit */
export interface SubscriptionClaimAuditInitializer {
  /** Default value: nextval('subscription_claim_audit_id_seq'::regclass) */
  id?: SubscriptionClaimAuditId;

  user_id: number;

  email_hash: string;

  ip_hash: string;

  outcome: string;

  /** Default value: now() */
  created_at?: Date;
}

/** Represents the mutator for the table public.subscription_claim_audit */
export interface SubscriptionClaimAuditMutator {
  id?: SubscriptionClaimAuditId;

  user_id?: number;

  email_hash?: string;

  ip_hash?: string;

  outcome?: string;

  created_at?: Date;
}
