// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.suppression_events */
export type SuppressionEventsId = number & { __brand: 'public.suppression_events' };

/** Represents the table public.suppression_events */
export default interface SuppressionEvents {
  id: SuppressionEventsId;

  email_hash: string;

  event_type: string;

  sg_event_id: string;

  event_at: Date;

  created_at: Date;
}

/** Represents the initializer for the table public.suppression_events */
export interface SuppressionEventsInitializer {
  /** Default value: nextval('suppression_events_id_seq'::regclass) */
  id?: SuppressionEventsId;

  email_hash: string;

  event_type: string;

  sg_event_id: string;

  event_at: Date;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.suppression_events */
export interface SuppressionEventsMutator {
  id?: SuppressionEventsId;

  email_hash?: string;

  event_type?: string;

  sg_event_id?: string;

  event_at?: Date;

  created_at?: Date;
}
