// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.trial_ended_emails */
export type TrialEndedEmailsId = number & { __brand: 'public.trial_ended_emails' };

/** Represents the table public.trial_ended_emails */
export default interface TrialEndedEmails {
  id: TrialEndedEmailsId;

  user_id: UsersId;

  token: string;

  sent_at: Date;
}

/** Represents the initializer for the table public.trial_ended_emails */
export interface TrialEndedEmailsInitializer {
  /** Default value: nextval('trial_ended_emails_id_seq'::regclass) */
  id?: TrialEndedEmailsId;

  user_id: UsersId;

  token: string;

  /** Default value: CURRENT_TIMESTAMP */
  sent_at?: Date;
}

/** Represents the mutator for the table public.trial_ended_emails */
export interface TrialEndedEmailsMutator {
  id?: TrialEndedEmailsId;

  user_id?: UsersId;

  token?: string;

  sent_at?: Date;
}
