// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.unsupported_notion_blocks */
export type UnsupportedNotionBlocksBlockType = string & { __brand: 'public.unsupported_notion_blocks' };

/** Represents the table public.unsupported_notion_blocks */
export default interface UnsupportedNotionBlocks {
  block_type: UnsupportedNotionBlocksBlockType;

  occurrences: string;

  first_seen: Date;

  last_seen: Date;
}

/** Represents the initializer for the table public.unsupported_notion_blocks */
export interface UnsupportedNotionBlocksInitializer {
  block_type: UnsupportedNotionBlocksBlockType;

  /** Default value: '0'::bigint */
  occurrences?: string;

  /** Default value: CURRENT_TIMESTAMP */
  first_seen?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  last_seen?: Date;
}

/** Represents the mutator for the table public.unsupported_notion_blocks */
export interface UnsupportedNotionBlocksMutator {
  block_type?: UnsupportedNotionBlocksBlockType;

  occurrences?: string;

  first_seen?: Date;

  last_seen?: Date;
}
