// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.user_surveys */
export type UserSurveysId = number & { __brand: 'public.user_surveys' };

/** Represents the table public.user_surveys */
export default interface UserSurveys {
  id: UserSurveysId;

  user_id: UsersId;

  survey_key: string;

  improvement: string | null;

  studying: string | null;

  status: string;

  created_at: Date;

  updated_at: Date;
}

/** Represents the initializer for the table public.user_surveys */
export interface UserSurveysInitializer {
  /** Default value: nextval('user_surveys_id_seq'::regclass) */
  id?: UserSurveysId;

  user_id: UsersId;

  /** Default value: 'post_login_v1'::text */
  survey_key?: string;

  improvement?: string | null;

  studying?: string | null;

  status: string;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  updated_at?: Date;
}

/** Represents the mutator for the table public.user_surveys */
export interface UserSurveysMutator {
  id?: UserSurveysId;

  user_id?: UsersId;

  survey_key?: string;

  improvement?: string | null;

  studying?: string | null;

  status?: string;

  created_at?: Date;

  updated_at?: Date;
}
