// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersId } from './Users';

/** Identifier type for public.user_visible_errors */
export type UserVisibleErrorsId = string & { __brand: 'public.user_visible_errors' };

/** Represents the table public.user_visible_errors */
export default interface UserVisibleErrors {
  id: UserVisibleErrorsId;

  user_id: UsersId | null;

  surface: string;

  code: string;

  context: unknown | null;

  occurred_at: Date;
}

/** Represents the initializer for the table public.user_visible_errors */
export interface UserVisibleErrorsInitializer {
  /** Default value: gen_random_uuid() */
  id?: UserVisibleErrorsId;

  user_id?: UsersId | null;

  surface: string;

  code: string;

  context?: unknown | null;

  /** Default value: CURRENT_TIMESTAMP */
  occurred_at?: Date;
}

/** Represents the mutator for the table public.user_visible_errors */
export interface UserVisibleErrorsMutator {
  id?: UserVisibleErrorsId;

  user_id?: UsersId | null;

  surface?: string;

  code?: string;

  context?: unknown | null;

  occurred_at?: Date;
}
