import { useEffect, useMemo, useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { Link, Navigate, useNavigate, useSearchParams } from 'react-router-dom';
import { ErrorHandlerType } from '../../components/errors/helpers/getErrorMessage';
import { track } from '../../lib/analytics/track';
import { storePassToken } from '../../lib/anonymousPass';
import useQuery from '../../lib/hooks/useQuery';
import { useUserLocals } from '../../lib/hooks/useUserLocals';
import styles from '../../styles/shared.module.css';
import { ExploreCard } from './components/ExploreCard/ExploreCard';
import { OnboardingTour } from './components/OnboardingTour/OnboardingTour';
import UploadForm from './components/UploadForm/UploadForm';
import pageStyles from './UploadPage.module.css';

const REATTACH_KEY = 'upload_pending_filename';

interface Props {
  setErrorMessage: ErrorHandlerType;
}

export function UploadPage({ setErrorMessage }: Readonly<Props>) {
  const query = useQuery();
  const view = query.get('view');
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [reattachFilename, setReattachFilename] = useState<string | null>(() => {
    const stored = globalThis.sessionStorage?.getItem(REATTACH_KEY) ?? null;
    return stored != null && stored.length > 0 ? stored : null;
  });
  const { data: userLocals } = useUserLocals();

  const isSignedIn = userLocals?.user?.id != null;
  const isAiOn = useMemo(() => {
    if (!isSignedIn) return false;
    return globalThis.localStorage?.getItem('claude-ai-flashcards') === 'true';
  }, [isSignedIn]);
  const aiBadgeState: 'anon' | 'on' | 'off' = useMemo(() => {
    if (!isSignedIn) return 'anon';
    return isAiOn ? 'on' : 'off';
  }, [isSignedIn, isAiOn]);

  useEffect(() => {
    if (aiBadgeState === 'anon') track('upload_ai_anon_badge_viewed');
    else if (aiBadgeState === 'on') track('upload_ai_on_badge_viewed');
    else track('upload_ai_off_badge_viewed');
  }, [aiBadgeState]);

  useEffect(() => {
    if (searchParams.get('from') === 'pass') {
      const next = new URLSearchParams(searchParams);
      next.delete('from');
      const qs = next.toString();
      navigate(qs ? `/upload?${qs}` : '/upload', { replace: true });
    }
  }, [searchParams, navigate]);

  useEffect(() => {
    const passSession = searchParams.get('pass_session');
    if (passSession != null && passSession.length > 0) {
      // Owner decision: anonymous passes live in the browser (localStorage is sanctioned for this use case)
      storePassToken(passSession);
      const next = new URLSearchParams(searchParams);
      next.delete('pass_session');
      const qs = next.toString();
      navigate(qs ? `/upload?${qs}` : '/upload', { replace: true });
    }
  }, [searchParams, navigate]);

  if (
    view === 'template' ||
    view === 'deck-options' ||
    view === 'card-options'
  ) {
    return <Navigate to="/card-options" replace />;
  }

  return (
    <div className={styles.page}>
      <Helmet>
        <title>Upload — 2anki</title>
      </Helmet>
      <header className={styles.pageHeader}>
        <h1 className={styles.title}>Convert your notes</h1>
        <p className={styles.subtitle}>
          Drop a file and get a clean Anki deck in seconds
        </p>
      </header>
      <OnboardingTour
        createdAt={userLocals?.user?.created_at ?? null}
        onboardedAt={userLocals?.user?.onboarded_at ?? null}
      />
      {reattachFilename != null && (
        <div className={pageStyles.reattachBanner} role="status">
          <span>Re-attach </span>
          <strong>{reattachFilename}</strong>
          <span> to convert</span>
        </div>
      )}
      <div className={styles.aiOffBadge} role="status">
        {aiBadgeState === 'on' && (
          <>
            <span className={styles.badgeSuccess}>AI is on</span>
            <span className={styles.aiOffBadgeBody}>
              {' '}Cards are generated by Claude.{' '}
              <Link
                to="/card-options?returnTo=/upload#pdf-ai"
                onClick={() => track('upload_ai_on_badge_clicked')}
              >
                Manage in Settings
              </Link>
              .
            </span>
          </>
        )}
        {aiBadgeState === 'off' && (
          <>
            <span className={styles.badgeWarning}>AI is off</span>
            <span className={styles.aiOffBadgeBody}>
              {' '}Turn it on in{' '}
              <Link
                to="/card-options?returnTo=/upload#pdf-ai"
                onClick={() => track('upload_ai_off_badge_clicked')}
              >
                Settings
              </Link>
              .
            </span>
          </>
        )}
        {aiBadgeState === 'anon' && (
          <>
            <span className={styles.badgeWarning}>AI is off</span>
            <span className={styles.aiOffBadgeBody}>
              {' '}
              <Link
                to="/login?redirect=/card-options"
                onClick={() => track('upload_ai_anon_badge_clicked')}
              >
                Sign in to turn it on
              </Link>
              .
            </span>
          </>
        )}
      </div>
      <UploadForm setErrorMessage={setErrorMessage} aiOn={isAiOn} />
      <ExploreCard />
      <section className={pageStyles.howItWorks}>
        <h2 className={pageStyles.howItWorksHeading}>How it works</h2>
        <p className={pageStyles.footnote}>
          Files are deleted after 2 hours.
        </p>
        <div className={pageStyles.steps}>
          <div className={pageStyles.step}>
            <span className={pageStyles.stepNumber}>1</span>
            <div>
              <p className={pageStyles.stepTitle}>Drop or choose a file</p>
              <p className={pageStyles.stepBody}>
                PDF, Word, Notion export, Markdown, HTML, Excel, CSV, or PowerPoint. In Word docs, headings become card fronts and the body text under each heading becomes the back.
              </p>
              <p className={pageStyles.stepBody}>
                Coming from Notion?{' '}
                <a href="/documentation/start-here/upload-a-file">
                  How to export your pages.
                </a>
              </p>
            </div>
          </div>
          <div className={pageStyles.step}>
            <span className={pageStyles.stepNumber}>2</span>
            <div>
              <p className={pageStyles.stepTitle}>Your deck is built</p>
              <p className={pageStyles.stepBody}>
                Images, code blocks, cloze, and formatting carry over. Usually a few seconds.
              </p>
            </div>
          </div>
          <div className={pageStyles.step}>
            <span className={pageStyles.stepNumber}>3</span>
            <div>
              <p className={pageStyles.stepTitle}>Open in Anki</p>
              <p className={pageStyles.stepBody}>
                Your .apkg downloads automatically. Import it into Anki or AnkiDroid to start studying.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className={pageStyles.contactNudge} aria-label="Contact us">
        <p>
          Something not working?{' '}
          <Link to="/contact">Tell us</Link> or email{' '}
          <a href="mailto:support@2anki.net">support@2anki.net</a>.
        </p>
      </section>
    </div>
  );
}
